[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "particle-tools"
version = "0.1.0"

[dependencies]
byteorder = "1.0.0"
clap = "2.24.2"
crc = "1.4.0"
error-chain = "0.10.0"
sha2 = "0.5.2"
tempdir = "0.3.5"
